import { createClient } from "@/lib/supabase/server";

interface TodoItem {
  id: number;
  name: string;
  is_completed: boolean;
  created_at: string;
}

export default async function TodosPage() {
  const supabase = await createClient();

  // Kita bypass pengecekan tipe Database dengan (supabase as any)
  // karena tabel 'todos' mungkin belum ada di tipe skema lokal (Database) Anda.
  const { data, error } = await (supabase as any)
    .from("todos")
    .select("*") as { data: TodoItem[] | null; error: any };

  return (
    <div className="container mx-auto p-8 max-w-xl">
      <h1 className="text-2xl font-bold mb-6 font-brand">Uji Koneksi Supabase: Todos</h1>
      
      {error ? (
        <div className="p-5 mb-6 rounded-md bg-destructive/10 text-destructive border border-destructive/20 text-sm space-y-4">
          <div>
            <p className="font-semibold text-base mb-1">Gagal memuat tabel 'todos'</p>
            <p className="text-xs opacity-90">Error Code: {error.code} | {error.message}</p>
          </div>
          <p>
            Tabel <code className="bg-destructive/15 px-1.5 py-0.5 rounded font-mono text-xs">todos</code> kemungkinan besar belum dibuat di database Supabase Anda.
          </p>
          <div className="space-y-2">
            <p className="font-semibold">Salin dan jalankan perintah SQL berikut di SQL Editor Supabase Anda:</p>
            <pre className="bg-slate-900 text-slate-100 p-4 rounded font-mono text-xs overflow-x-auto whitespace-pre-wrap select-all border border-slate-800">
{`CREATE TABLE public.todos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  is_completed boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- Aktifkan RLS (Row Level Security)
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- Izinkan semua pengguna membaca & menulis (untuk keperluan testing)
CREATE POLICY "Allow public read access" ON public.todos FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON public.todos FOR INSERT WITH CHECK (true);

-- Tambahkan data sampel
INSERT INTO public.todos (name) VALUES 
('Membeli kopi'), 
('Membaca dokumentasi Supabase'), 
('Membuat aplikasi keuangan');`}
            </pre>
          </div>
        </div>
      ) : (
        <div className="space-y-4">
          <p className="text-emerald-600 bg-emerald-50 border border-emerald-200 rounded px-3 py-2 text-sm font-medium">
            ✔ Berhasil terhubung ke Supabase!
          </p>
          <ul className="space-y-3">
            {data && data.length > 0 ? (
              data.map((todo) => (
                <li 
                  key={todo.id} 
                  className="flex items-center gap-3 p-3 rounded-md border border-border bg-surface hover:bg-muted/30 transition-colors"
                >
                  <input 
                    type="checkbox" 
                    checked={todo.is_completed || false} 
                    readOnly 
                    className="rounded border-gray-300 text-primary focus:ring-primary h-4 w-4"
                  />
                  <span className={todo.is_completed ? "line-through text-muted-foreground" : "text-foreground font-medium"}>
                    {todo.name}
                  </span>
                </li>
              ))
            ) : (
              <p className="text-muted-foreground text-sm text-center py-8">Tabel 'todos' kosong. Silakan tambahkan data baru!</p>
            )}
          </ul>
        </div>
      )}
      
      <div className="mt-8 pt-6 border-t border-border flex flex-col gap-2 text-xs text-muted-foreground">
        <span>Supabase URL: <code className="font-mono bg-muted px-1 py-0.5 rounded">{process.env.NEXT_PUBLIC_SUPABASE_URL}</code></span>
        <a href="/" className="text-primary hover:underline font-medium mt-2">← Kembali ke Beranda</a>
      </div>
    </div>
  );
}
